# Generated by Django 3.0.8 on 2020-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='메인 사진'),
        ),
    ]
